# Generated by Django 5.2.9 on 2026-01-20 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_add_direct_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available_as_mentor', models.BooleanField(default=False)),
                ('is_seeking_mentor', models.BooleanField(default=False)),
                ('mentor_topics', models.TextField(blank=True, help_text='Topics you can mentor on (comma separated)')),
                ('seeking_topics', models.TextField(blank=True, help_text='Topics you want to learn about (comma separated)')),
                ('experience', models.TextField(blank=True, help_text='Brief description of your experience')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
