# Generated by Django 5.2.9 on 2026-01-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_add_mentor_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
